### ISSUE TITLE
Concurrent downloads not working

### ISSUE THREAD

**Issue by Synchrones** [theogravity/electron-dl-manager#11]
Hi, 
In my app, I need to download a fairly large amount of files and as the electron-dl library was not working for concurrent downloads I ended up switching to your library.
From what I understood, it is supposed to be able to download multiple files at the same time but unfortunatly it's not working for me. I created a blank project to test it and when trying to start 2 downloads back to back here is what happens : 
-the fastest downloaded file is saved with the name given in the second download
-the second one isn't downloaded and a "save as" prompt appears in the app

I'm using electron v31.3.1 and here is what my download code looks like : 
```
ipcMain.on('download', () => {
  manager.download({window:BrowserWindow.getAllWindows()[0], url:"https://lh3.ggpht.com/p/AF1QipNYslO0dH6gUzQdT9Bm6qSIPSRhqM69-1IM4w1v=x0-y0-z4", directory: app.getAppPath() + '/download/', saveAsFilename:"test1.jpg", callbacks: {}});
  manager.download({window:BrowserWindow.getAllWindows()[0], url:"https://lh3.ggpht.com/p/AF1QipNYslO0dH6gUzQdT9Bm6qSIPSRhqM69-1IM4w1v=x0-y5-z4", directory: app.getAppPath() + '/download/', saveAsFilename:"test2.jpg", callbacks: {}});
})
```
Did you manage to get multiple downloads working at the same time? If so I'm curious to see how you did it because it doesn't seems that my code shouldn't work...

Also, I don't know if it's really a bug but not declaring the callback argument returns an error saying it's trying to read one of it's propriety so I need to add it event if it's let empty.

**Comment by theogravity** [comment]
I shall take a look. Thanks for reporting this!

**Comment by theogravity** [comment]
So I used the exact same code you used, and I did see the issue when `await` wasn't applied, but it was fine when it was:

```
    await manager.download({window: BrowserWindow.getAllWindows()[0], url:"https://lh3.ggpht.com/p/AF1QipNYslO0dH6gUzQdT9Bm6qSIPSRhqM69-1IM4w1v=x0-y0-z4", directory: __dirname + '/download/', saveAsFilename:"test1.jpg", callbacks: {}});
    await manager.download({window: BrowserWindow.getAllWindows()[0], url:"https://lh3.ggpht.com/p/AF1QipNYslO0dH6gUzQdT9Bm6qSIPSRhqM69-1IM4w1v=x0-y5-z4", directory: __dirname + '/download/', saveAsFilename:"test2.jpg", callbacks: {}});
```

Try with `await`. Let me know if this fixes it

**Comment by theogravity** [comment]
Also, you can also do debug logging to see what it's doing internally:

```
    const manager = new ElectronDownloadManager({
      debugLogger: message => console.log(message)
    });
```

If you install `3.1.1`, I added more debug messages to also inform that a download as completed.

**Comment by theogravity** [comment]
Also in 99% of cases, it's not usually an issue to call a promise "out-of-band" (as in without `await`), but the Electron APIs around download management has an extremely wonky implementation that even I had to do some tricks to get certain things to work correctly in the library code. 

So I'm not surprised that you're experiencing strange behavior when `await` isn't called when using `download()`.

**Comment by Synchrones** [comment]
Thanks a lot for your response, I tried some of the things you told me and I think I have found a way to make it work!
Adding the await keyword worked and the files are being downloaded correctly, as I was used to the electron-dl library, I didn't realized that the promise was resolved almost immedialty to return the id (whereas it was resolved when the file finished downloading in the previous library), I thought adding an await keyword would make the files download one after another.
Using promise.all() is not working though, here is what I get in the logs : 

With 2 await : 
```
[4f4898] Registering download for url: https://lh3.ggpht.com/p/AF1QipNYslO0dH6gUzQdT9Bm6q...
[4f4898] Setting save path to C:\Users\Axou\Desktop\download test\download\test1.jpg
[4f4898] Initiating download item handlers
[5677c3] Registering download for url: https://lh3.ggpht.com/p/AF1QipNYslO0dH6gUzQdT9Bm6q...
[5677c3] Setting save path to C:\Users\Axou\Desktop\download test\download\test2.jpg
[5677c3] Initiating download item handlers
[4f4898] Download completed. Total bytes: 9833
[4f4898] Cleaning up download item event listeners
[5677c3] Download completed. Total bytes: 112970
[5677c3] Cleaning up download item event listeners
```

With promise.all() : 
```
[11638f] Registering download for url: https://lh3.ggpht.com/p/AF1QipNYslO0dH6gUzQdT9Bm6q...
[f7e14f] Registering download for url: https://lh3.ggpht.com/p/AF1QipNYslO0dH6gUzQdT9Bm6q...
[11638f] Setting save path to C:\Users\Axou\Desktop\download test\download\test1.jpg
[11638f] Initiating download item handlers
[f7e14f] Setting save path to C:\Users\Axou\Desktop\download test\download\test2.jpg
[f7e14f] Initiating download item handlers
[11638f] Download completed. Total bytes: 9833
[f7e14f] Download completed. Total bytes: 9833
[11638f] Cleaning up download item event listeners
[f7e14f] Cleaning up download item event listeners
```
It seems like not waiting for the first promise to resolve is causing the second one to interfer with the first.

**Comment by theogravity** [comment]
`Promise.all()` executes promises in parallel, so the behavior is correct. Are you looking to execute them sequentially? If so, then the non-all version is what you want. You can also use a `for await` loop for sequential as well if you have an array of items:

```
  const downloads = [async () => await manager.download({window: BrowserWindow.getAllWindows()[0], url:"https://lh3.ggpht.com/p/AF1QipNYslO0dH6gUzQdT9Bm6qSIPSRhqM69-1IM4w1v=x0-y0-z4", directory: __dirname + '/download/', saveAsFilename:"test1.jpg", callbacks: {}})];
  for await (const download of downloads) {
...
  }
  ```

**Comment by rtritto** [comment]
Same problem here: I tested with 2 download at same time (in _manager.download_, _directory_ isn't empty) and I get the "Save as" popup only for 1 download.

**Comment by theogravity** [comment]
> Same problem here: I tested with 2 download at same time (in _manager.download_, _directory_ isn't empty) and I get the "Save as" popup only for 1 download.

This is after applying `await` to both?

**Comment by theogravity** [comment]
> 9833
> [f7e14f] Download completed. Total bytes: 9833

Oh I see, the download bytes are the same when they shouldn't be. Yeah, that's really strange. I'll continue looking into this.

**Comment by theogravity** [comment]
The line where I initially get the `DownloadItem` from Electron is:

https://github.com/theogravity/electron-dl-manager/blob/main/src/DownloadInitiator.ts#L111

I won't be able to play with this until my work day ends (It's 9:30AM PST here, so I prob won't get to this in 8+ hours).

You can play around with it by cloning this repo and linking:

- `npm install` in the cloned repo
- `npm run build` to build the project (any changes you make you'd have to re-run this command)
- `npm link` to create a link to the built code

Then in your own project do `npm link electron-dl-manager` to use the locally cloned version.

**Comment by rtritto** [comment]
From front end page, in the on click event:
```ts
const handleDownloadSelected = async (downloadLink: string, directory: string) => {
  await Promise.allSettled(downloadLinks.map((downloadLink) => window.electronApi.ipcRenderer.send(<DOWNLOAD_BY_URL>, { downloadLink, directory }))
}
```

In the `main` page:
```ts
ipcMain.on(<DOWNLOAD_BY_URL>, async (_, { downloadLink, directory }): Promise<void> => {
  await manager.download({
    window,
    url: downloadLink,
    directory,
    ...
  })
})
```

**Comment by theogravity** [comment]
When one calls `DownloadManager.download()`:

https://github.com/theogravity/electron-dl-manager/blob/main/src/ElectronDownloadManager.ts#L90

It's always creating a new instance of `DownloadInitiator`. And `DownloadInitiator` does the following:

- creates a new instance of `CallbackDispatcher`, which is used to communicate back to the `DownloadManager` / user for status updates
- creates a new instance of `DownloadData`, of which one of the properties is `item`, which is the reference to the Electron `DownloadItem` where I get the download data from.

If there is a bug it's going to be either something around how `DownloadData` is assigned / pulls values, or `CallbackDispatcher`. Worse-case, it's an actual bug in Electron itself.

In general, the downloads shouldn't cross because they're created in their own instances of `DownloadInitiator`, but not sure what's going on at the top of my head here.

**Comment by theogravity** [comment]
Writing down the process really helped. I think I know what's going on.

I'm expecting that `will-download` will trigger right when `downloadURL` is called, but based on what you both have reported, it doesn't seem to be guaranteed that will happen in a "sequential" fashion.

So in the situation where you register two downloads at the same time (assuming we're doing it properly by calling with `await`):

- Two event handlers for `will-download` gets registered
- Then `downloadURL` gets called, meaning that `will-download` *eventually* fire (as opposed to immediate), and if that eventually is really "late", then that means both of the download instances will get the instance of the first `DownloadItem`.

There should be a way to fix this (maybe some internal queue that ensures that we only listen to `will-download` once at a time only before processing the next download request).

Thanks for the reports. I'll look into a fix tonight.

**Comment by rtritto** [comment]
> Thanks a lot for your response, I tried some of the things you told me and I think I have found a way to make it work! Adding the await keyword worked and the files are being downloaded correctly, as I was used to the electron-dl library, I didn't realized that the promise was resolved almost immedialty to return the id (whereas it was resolved when the file finished downloading in the previous library), I thought adding an await keyword would make the files download one after another. Using promise.all() is not working though, here is what I get in the logs :
> 
> With 2 await :
> 
> ```
> [4f4898] Registering download for url: https://lh3.ggpht.com/p/AF1QipNYslO0dH6gUzQdT9Bm6q...
> [4f4898] Setting save path to C:\Users\Axou\Desktop\download test\download\test1.jpg
> [4f4898] Initiating download item handlers
> [5677c3] Registering download for url: https://lh3.ggpht.com/p/AF1QipNYslO0dH6gUzQdT9Bm6q...
> [5677c3] Setting save path to C:\Users\Axou\Desktop\download test\download\test2.jpg
> [5677c3] Initiating download item handlers
> [4f4898] Download completed. Total bytes: 9833
> [4f4898] Cleaning up download item event listeners
> [5677c3] Download completed. Total bytes: 112970
> [5677c3] Cleaning up download item event listeners
> ```
> 
> With promise.all() :
> 
> ```
> [11638f] Registering download for url: https://lh3.ggpht.com/p/AF1QipNYslO0dH6gUzQdT9Bm6q...
> [f7e14f] Registering download for url: https://lh3.ggpht.com/p/AF1QipNYslO0dH6gUzQdT9Bm6q...
> [11638f] Setting save path to C:\Users\Axou\Desktop\download test\download\test1.jpg
> [11638f] Initiating download item handlers
> [f7e14f] Setting save path to C:\Users\Axou\Desktop\download test\download\test2.jpg
> [f7e14f] Initiating download item handlers
> [11638f] Download completed. Total bytes: 9833
> [f7e14f] Download completed. Total bytes: 9833
> [11638f] Cleaning up download item event listeners
> [f7e14f] Cleaning up download item event listeners
> ```
> 
> It seems like not waiting for the first promise to resolve is causing the second one to interfer with the first.

Some considerations for the _Promise.all_ case:
- only the first download started (9833 size is on logs)
- second download doesn't start because of the "Save as" popup (112970 size isn't on logs)

**Comment by theogravity** [comment]
Sorry, been really busy at work. I did take a small stab at it in the past hour, and I thought I could use something like a promise-based mutex, but unfortunately it doesn't work when more than two downloads involved (as the subsequent downloads would all end up executing at the same time as opposed to "sequentially").

I'm trying to basically make sure that we only start the next download once the previous `will-download` has been triggered.

It's going to require some kind of internal queue of some sort. Unfortunately out of energy for the day to look into it further.

If any of you want to attempt a fix, I'd really appreciate it. I'm testing against the situation where someone does:

```
await Promise.all([
  manager.download(...),
  manager.download(...),
  manager.download(...),
  manager.download(...),
])
```

**Comment by rtritto** [comment]
Did you try creating a new function as multiple downloads?
```ts
await manager.downloadMultiple({
  window: mainWindow,
  directory,
  urls: [
    <URL_1>,
    <URL_2>
  ]
})
```
Maybe internally you should create a single instance and the trigger the start(s) of all download(s).

**Comment by theogravity** [comment]
Ok, I ended up implementing an async queue. I tested the following situations:

- Promise.all against 4 downloads
- 4 downloads without an await call

(I forgot to test straight await, but should work as well)

Published as `3.2.0`. Thanks for your patience. Please re-open if parallel downloads are still an issue.

**Comment by bfan1256** [comment]
I know this supports multiple downloads (and I can pass it into the queue), but does it actually send out multiple requests simultaneously? It feels like I'm seeing all of my requests going out quite sequentially and I can't seem to saturate my bandwidth. 

My log output seems super linear (1 by 1) instead of multiple in parallel...

**Comment by theogravity** [comment]
> I know this supports multiple downloads (and I can pass it into the queue), but does it actually send out multiple requests simultaneously? It feels like I'm seeing all of my requests going out quite sequentially and I can't seem to saturate my bandwidth. 
> 
> My log output seems super linear (1 by 1) instead of multiple in parallel...

Would help to see the code. Is this with `Promise.all()`?

**Comment by bfan1256** [comment]
```typescript
constructor() {
    this.maxConcurrent = 500;
    this.manager = new ElectronDownloadManager({
      debugLogger: message => console.log(message)
    });
  }

  enqueue(item: DownloadQueueObj) {
    this.queue.push(item);
    this.startNextDownloads();
  }

  private startNextDownloads() {
    // As long as we have queue items *and* we haven’t hit maxConcurrent,
    // dequeue one (or a small handful), fire it off
    // , and immediately loop.
    console.log('Queue Length', this.queue.length)
    while (this.queue.length > 0 && this.numActive < this.maxConcurrent) {
      const batchSize = Math.min(30, this.queue.length); // Limit batch size to 30
      const batch = this.queue.splice(0, batchSize); // Dequeue up to 30 items

      batch.forEach((queueObj) => {
        this.numActive++;
        console.log(this.numActive);

        this._download(queueObj)
          .finally(() => {
            this.numActive--;
            // As soon as one finishes, try to start another
            this.startNextDownloads();
          });
      });
    }
  }

  private async _download(queueObj: DownloadQueueObj) {
    const window: BrowserWindow = getMainWindow();
    const { downloadObject, downloadUrl } = queueObj;

    const directoryNode = downloadObject.transferData.nodes.find(
      (n) => n.level === TransferStatusLevel.DIRECTORY
    );
    const fileNode = downloadObject.transferData.nodes.find(
      (n) => n.level === TransferStatusLevel.FILE
    );
    const downloadId = directoryNode ? directoryNode.id : fileNode!.id;

    try {
      // If the node represents a directory, create locally and immediately signal completion
      if (downloadObject.objType === "DIRECTORY") {
        fs.mkdir(
          getLocalDownloadPath(
            downloadObject.localPath,
            downloadObject.downloadDirectoryPath
          ),
          { recursive: false },
          (err) => {
            // ignore errors for now
          }
        );
        window.webContents.send("download-complete", {
          downloadObjSerialized: downloadObject,
        });
        return;
      }

      // Build the download parameters for electron-download-manager
      const saveDir =
        downloadObject.downloadDirectoryPath || getDownloadDirectoryPath();
      const saveFilename = downloadObject.localPath;

      const downloadParams = {
        window,
        url: downloadUrl,
        saveAsFilename: saveFilename,
        directory: saveDir,
        callbacks: {
          onDownloadStarted: async ({
                                      id: mgrId,
                                      item,
                                      resolvedFilename,
                                    }) => {
            this.managerIdMap.set(downloadId, mgrId);
            window.webContents.send("download-started", {
              id: mgrId,
              filename: resolvedFilename,
              totalBytes: item.getTotalBytes(),
              downloadObjSerialized: downloadObject,
            });
          },
          onDownloadProgress: async ({ id: mgrId, item, percentCompleted }: DownloadData) => {
            window.webContents.send("download-progress", {
              id: mgrId,
              percentCompleted,
              bytesReceived: item.getReceivedBytes(),

              downloadObjSerialized: downloadObject,
            });
          },
          onDownloadCompleted: async ({ id: mgrId, item }) => {
            window.webContents.send("download-complete", {
              id: mgrId,
              filePath: item.getSavePath(),
              downloadObjSerialized: downloadObject,
            });
            this.managerIdMap.delete(downloadId);
          },
          onDownloadCancelled: async ({ id: mgrId, item }) => {
            window.webContents.send("download-cancel", {
              id: mgrId,
              downloadObjSerialized: downloadObject,
            });
            this.managerIdMap.delete(downloadId);
          },
          onError: (err: Error, data: any) => {
            window.webContents.send("download-error", {
              error: err,
              downloadObjSerialized: downloadObject,
            });
            this.managerIdMap.delete(downloadId);
          },
        },
      };

      return this.manager.download(downloadParams);
    } catch (e) {
      window.webContents.send("download-error", {
        error: e,
        downloadObjSerialized: downloadObject,
      });
      this.managerIdMap.delete(downloadId);
    }
  }
```

**Comment by theogravity** [comment]
The code looks fine on initial inspection to me. 

What are the file sizes of the downloads? If they're pretty small, then it might hard to see saturation. Where are the downloads happening (is it local network, remote HTTP?)

**Comment by theogravity** [comment]
I pasted your sample code to Claude and one thing it brought up that might be an issue is that if you're downloading from the same domain, you'll hit a 6-8 active connection limit for it. It's a general browser limitation. I'm not sure what happens when you go beyond the limit (I'm guessing it throttles).

https://claude.ai/share/f819e74c-888d-4d6a-b7fc-273fed0751bd
